config:
  service:
    name: jackson-api
    port: 8080
    labelName: jackson
    canaryWeight: 10
    stableWeight: 90
  appName: spring-boot-api
  enableVirtualService: false # temp disable for demo
  enableDestinationRule: false # temp disable for demo
subcomponents:
  canary:
    config:
      appName: spring-boot-api
      fullnameOverride: api-deploy-canary
  stable:
    config:
      appName: spring-boot-api
      fullnameOverride: api-deploy-stable
